[project]
name = "chatter-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "psycopg[binary]>=3.2.1",
  "google-generativeai>=0.8.3",
  "google-auth>=2.23.0",
  "python-dotenv>=1.0.0",
]
